version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zaavero
    ports:
      - "5433:5432"
    volumes:
      - zaavero_pg:/var/lib/postgresql/data

volumes:
  zaavero_pg:
