import Link from "next/link";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ThemeToggleButton } from "@/components/theme-toggle";

const features = [
  {
    title: "7 databases, one interface",
    body: "Connect Postgres, MySQL, SQL Server, Snowflake, BigQuery, Databricks, and Redshift — all with encrypted credentials and one-click testing.",
  },
  {
    title: "AI SQL with conversation memory",
    body: "Ask follow-up questions naturally. The AI remembers prior context, uses your real schema, and generates dialect-perfect SQL.",
  },
  {
    title: "Lineage & validation",
    body: "Auto-inferred table relationships, join path discovery, multi-dialect SQL validation, and read-only enforcement — no dangerous ops ever.",
  },
  {
    title: "Data Crawler",
    body: "Crawl GitHub repos, dbt projects, and data pipelines to build end-to-end lineage. Know where data comes from and where it goes.",
  },
  {
    title: "Charts, insights & caching",
    body: "7 chart types with auto-detection, KPI cards, pivot tables, CSV export, and smart query caching for instant repeats.",
  },
];

const plans = [
  { name: "Starter", price: "$49", detail: "3 connections · 2k AI queries / mo" },
  { name: "Team", price: "$149", detail: "15 connections · 20k AI queries / mo · SSO-ready" },
  { name: "Enterprise", price: "Custom", detail: "VPC deploy · audit logs · dedicated support" },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen">
      <header className="border-b border-[hsl(var(--border))] backdrop-blur bg-[hsl(var(--background))]/80 sticky top-0 z-10">
        <div className="mx-auto max-w-6xl flex items-center justify-between px-6 py-4">
          <span className="font-semibold text-[hsl(var(--primary))]">DataWhisper</span>
          <div className="flex items-center gap-2">
            <ThemeToggleButton />
            <Link href="/login">
              <Button variant="ghost" size="sm">
                Sign in
              </Button>
            </Link>
            <Link href="/login">
              <Button size="sm">Get started</Button>
            </Link>
          </div>
        </div>
      </header>

      <section className="mx-auto max-w-6xl px-6 py-20 md:py-28 grid md:grid-cols-2 gap-12 items-center">
        <div>
          <p className="text-sm uppercase tracking-[0.2em] text-[hsl(var(--muted-foreground))] mb-4">Analytics copilot</p>
          <h1 className="text-4xl md:text-5xl font-bold leading-tight">
            Ask in English.
            <span className="text-[hsl(var(--primary))]"> Get SQL, charts, and trust.</span>
          </h1>
          <p className="mt-6 text-lg text-[hsl(var(--muted-foreground))] max-w-xl">
            DataWhisper turns natural language into optimized, validated SQL against your live warehouses — with lineage-aware joins,
            read-only execution, and instant visualizations.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link href="/login">
              <Button size="lg">Start free trial</Button>
            </Link>
            <Link href="/login">
              <Button size="lg" variant="outline">
                View demo
              </Button>
            </Link>
          </div>
        </div>
        <div className="rounded-2xl border border-[hsl(var(--border))] bg-gradient-to-br from-[hsl(var(--primary))]/10 via-transparent to-sky-500/10 p-8 shadow-xl">
          <pre className="text-xs md:text-sm text-[hsl(var(--muted-foreground))] overflow-x-auto leading-relaxed">
            {`-- Generated by DataWhisper (validated)
SELECT o.id, o.total, c.region
FROM sales.orders o
JOIN sales.customers c
  ON o.customer_id = c.id
WHERE o.created_at >= CURRENT_DATE - 30
LIMIT 500;`}
          </pre>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 py-16 border-t border-[hsl(var(--border))]">
        <h2 className="text-2xl font-semibold mb-10 text-center">Built for real data teams</h2>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((f) => (
            <Card key={f.title}>
              <CardHeader>
                <CardTitle className="text-base">{f.title}</CardTitle>
                <CardDescription>{f.body}</CardDescription>
              </CardHeader>
            </Card>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 py-16 border-t border-[hsl(var(--border))]">
        <h2 className="text-2xl font-semibold mb-10 text-center">Pricing</h2>
        <div className="grid md:grid-cols-3 gap-6">
          {plans.map((p) => (
            <Card key={p.name} className={p.name === "Team" ? "border-[hsl(var(--primary))]/50 ring-1 ring-[hsl(var(--primary))]/30" : ""}>
              <CardHeader>
                <CardTitle>{p.name}</CardTitle>
                <CardDescription>{p.detail}</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-bold">{p.price}</p>
                <Link href="/login" className="mt-4 block">
                  <Button className="w-full" variant={p.name === "Team" ? "default" : "outline"}>
                    Choose {p.name}
                  </Button>
                </Link>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      <footer className="border-t border-[hsl(var(--border))] py-10 text-center text-sm text-[hsl(var(--muted-foreground))]">
        © {new Date().getFullYear()} DataWhisper · Production-ready NL→SQL SaaS
      </footer>
    </div>
  );
}
